apiVersion: v1
kind: Service
metadata:
  name: spalabfinal-restapi
  labels:
    app: spalabfinal
    tier: restapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: spalabfinal
    tier: restapi
