apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spalabfinal-restapi
  labels:
    app: spalabfinal
    tier: restapi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: spalabfinal
        tier: restapi
    spec:
      containers:
      - name: spalabfinal-app
        image: gcr.io/inductive-talon-203408/spa-lab-final:latest
        command: ["spa-lab-final"]
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8000
